# Cleaning

In [733]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('max_columns', 120)
pd.set_option('max_colwidth', 5000)
from pandas import DataFrame
import csv

loans = pd.read_csv('Loan_Training_1.csv', low_memory=False, encoding = "ISO-8859-1")
loans.shape

loans.columns = loans.columns.str.lower().str.replace(" ","_").str.replace(".","").str.replace("(", "").str.replace(")", "").str.replace("-","")
loans.head(n=5)

,loan_id,amount_requested,amount_funded_by_investors,interest_rate,loan_length,credit_grade,loan_title,loan_purpose,monthly_payment,total_amount_funded,debttoincome_ratio,city,state,home_ownership,monthly_income,fico_range,earliest_credit_line,open_credit_lines,total_credit_lines,revolving_credit_balance,revolving_line_utilization,inquiries_in_the_last_6_months,accounts_now_delinquent,delinquent_amount,delinquencies_last_2_yrs,months_since_last_delinquency,public_records_on_file,months_since_last_record,education,employment_length,status
0,2227104,12000,12000.00,13.11%,36 months,B4,Credit card refinancing,credit_card,404.97,12000,15.24%,KINGSBURG,CA,MORTGAGE,4166.67,690-694,11/25/89,10.0,24.0,20229.0,86.80%,0.0,0.0,0.0,0.0,34.0,0.0,NaN,NaN,7 years,0
1,1690660,2000,2000.00,17.27%,36 months,C5,Car financing,car,71.58,2000,12.07%,FORT LAUDERDALE,FL,OWN,2083.33,660-664,1/27/07,18.0,28.0,6175.0,36.80%,3.0,0.0,0.0,0.0,30.0,0.0,NaN,NaN,1 year,1
2,2301695,9000,9000.00,7.90%,36 months,A4,Bundle Loan,debt_consolidation,281.62,9000,20.01%,PEACHTREE CITY,GA,MORTGAGE,7750.00,690-694,2/26/97,9.0,39.0,11639.0,46.60%,0.0,0.0,0.0,2.0,10.0,0.0,NaN,NaN,< 1 year,0
3,844352,13000,13000.00,11.99%,36 months,B5,Payback,debt_consolidation,431.73,13000,7.59%,Minneapolis,MN,RENT,5833.33,705-709,10/3/00,12.0,26.0,6696.0,47.50%,1.0,0.0,0.0,0.0,58.0,0.0,NaN,NaN,5 years,1
4,330773,10000,1525.01,10.71%,36 months,B5,Business Loan,other,163.01,5000,12.48%,reno,NV,MORTGAGE,16666.67,700-704,3/21/88,20.0,30.0,53087.0,69.90%,1.0,0.0,0.0,0.0,45.0,0.0,NaN,NaN,< 1 year,0

In [734]:
loans_predict = pd.read_csv('Loan_ToPredict.csv', low_memory=False)
loans_predict.shape

loans_predict.columns = loans_predict.columns.str.lower().str.replace(" ","_").str.replace(".","").str.replace("(", "").str.replace(")", "").str.replace("-","")
loans_predict = loans_predict.rename(columns={'status_fully_paid=1,_not_paid=0': 'status'})

loans_predict.head(n=5)
#print (loans.dtypes)

,loan_id,amount_requested,amount_funded_by_investors,interest_rate,loan_length,credit_grade,loan_title,loan_purpose,monthly_payment,total_amount_funded,debttoincome_ratio,city,state,home_ownership,monthly_income,fico_range,earliest_credit_line,open_credit_lines,total_credit_lines,revolving_credit_balance,revolving_line_utilization,inquiries_in_the_last_6_months,accounts_now_delinquent,delinquent_amount,delinquencies_last_2_yrs,months_since_last_delinquency,public_records_on_file,months_since_last_record,education,employment_length,status
0,1856772,10000,10000.00,10.16%,36 months,B1,Home improvement,home_improvement,323.43,10000,17.45%,fort worth,TX,OWN,4458.33,730-734,11/29/85,18.0,35.0,9973.0,19.70%,1.0,0.0,0.0,0.0,NaN,1.0,86.0,NaN,4 years,?
1,544915,4800,4800.00,13.61%,36 months,C2,My Loan,debt_consolidation,163.15,4800,15.79%,CINCINNATI,OH,OWN,1647.00,675-679,6/13/04,10.0,13.0,6636.0,45.50%,0.0,0.0,0.0,0.0,39.0,0.0,NaN,NaN,< 1 year,?
2,2079551,10000,10000.00,12.12%,36 months,B3,consoliate,debt_consolidation,332.72,10000,14.84%,Highlands Ranch,CO,RENT,7333.33,710-714,7/20/89,8.0,40.0,14888.0,24.10%,2.0,0.0,0.0,1.0,8.0,0.0,NaN,NaN,n/a,?
3,2514828,5350,5350.00,15.80%,36 months,C3,Debt Consoldation,debt_consolidation,0.00,5350,21.36%,LITTLE ELM,TX,MORTGAGE,3333.33,675-679,11/10/02,9.0,18.0,9879.0,55.80%,1.0,0.0,0.0,1.0,12.0,0.0,NaN,NaN,1 year,?
4,396145,13000,2997.38,14.74%,36 months,D3,i always make my payment.,debt_consolidation,448.98,13000,16.39%,louisville,KY,MORTGAGE,2916.67,675-679,8/30/01,9.0,9.0,21124.0,87.30%,3.0,0.0,0.0,0.0,NaN,0.0,NaN,Jefferson Community College-Louisville,3 years,?

In [735]:
def clear_percent (row):
    try:
        d = float(row['interest_rate'][:-1])/100.
    except:
        d = None
    return d

def clear_percent_debt (row):
    try:
        d = float(row['debttoincomeratio'][:-1])/100.
    except:
        d = None
    return d

def clear_percent_revolving (row):
    try:
        d = float(row['revolving_line_utilization'][:-1])/100.
    except:
        d = None
    return d

loans['int_rate_clean'] = loans.apply (lambda row: clear_percent(row),axis=1)
loans['debttoincomeratio_clean'] = loans.apply (lambda row: clear_percent_debt(row),axis=1)
loans['revolving_line_utilization_clean'] = loans.apply (lambda row: clear_percent_revolving(row),axis=1)
loans.head()

loans_predict['int_rate_clean'] = loans_predict.apply (lambda row: clear_percent(row),axis=1)
loans_predict['debttoincomeratio_clean'] = loans_predict.apply (lambda row: clear_percent_debt(row),axis=1)
loans_predict['revolving_line_utilization_clean'] = loans_predict.apply (lambda row: clear_percent_revolving(row),axis=1)
loans_predict.head()

,loan_id,amount_requested,amount_funded_by_investors,interest_rate,loan_length,credit_grade,loan_title,loan_purpose,monthly_payment,total_amount_funded,debttoincome_ratio,city,state,home_ownership,monthly_income,fico_range,earliest_credit_line,open_credit_lines,total_credit_lines,revolving_credit_balance,revolving_line_utilization,inquiries_in_the_last_6_months,accounts_now_delinquent,delinquent_amount,delinquencies_last_2_yrs,months_since_last_delinquency,public_records_on_file,months_since_last_record,education,employment_length,status,int_rate_clean,debttoincomeratio_clean,revolving_line_utilization_clean
0,1856772,10000,10000.00,10.16%,36 months,B1,Home improvement,home_improvement,323.43,10000,17.45%,fort worth,TX,OWN,4458.33,730-734,11/29/85,18.0,35.0,9973.0,19.70%,1.0,0.0,0.0,0.0,NaN,1.0,86.0,NaN,4 years,?,0.1016,None,0.197
1,544915,4800,4800.00,13.61%,36 months,C2,My Loan,debt_consolidation,163.15,4800,15.79%,CINCINNATI,OH,OWN,1647.00,675-679,6/13/04,10.0,13.0,6636.0,45.50%,0.0,0.0,0.0,0.0,39.0,0.0,NaN,NaN,< 1 year,?,0.1361,None,0.455
2,2079551,10000,10000.00,12.12%,36 months,B3,consoliate,debt_consolidation,332.72,10000,14.84%,Highlands Ranch,CO,RENT,7333.33,710-714,7/20/89,8.0,40.0,14888.0,24.10%,2.0,0.0,0.0,1.0,8.0,0.0,NaN,NaN,n/a,?,0.1212,None,0.241
3,2514828,5350,5350.00,15.80%,36 months,C3,Debt Consoldation,debt_consolidation,0.00,5350,21.36%,LITTLE ELM,TX,MORTGAGE,3333.33,675-679,11/10/02,9.0,18.0,9879.0,55.80%,1.0,0.0,0.0,1.0,12.0,0.0,NaN,NaN,1 year,?,0.1580,None,0.558
4,396145,13000,2997.38,14.74%,36 months,D3,i always make my payment.,debt_consolidation,448.98,13000,16.39%,louisville,KY,MORTGAGE,2916.67,675-679,8/30/01,9.0,9.0,21124.0,87.30%,3.0,0.0,0.0,0.0,NaN,0.0,NaN,Jefferson Community College-Louisville,3 years,?,0.1474,None,0.873

In [736]:
def clear_term (row):
    try:
        if row['loan_length']=='36 months':
            d = 1
        else:
            if row['loan_length']=='60 months':
                d = 2
            else:
                if np.isnan(row['loan_length']):
                    d = None
                else:
                    print ('WRONG')
                    print (row['loan_length'])
    except:
        print ('EXCEPT')
        d = None
    return d

loans['loan_length_clean'] = loans.apply (lambda row: clear_term(row),axis=1)
loans_predict['loan_length_clean'] = loans_predict.apply (lambda row: clear_term(row),axis=1)

loans.head()

def clean_emp_length(argument):
    switcher = {
        '1 year': 1,
        '2 years': 2,
        '3 years': 3,
        '4 years': 4,
        '5 years': 5,
        '6 years': 6,
        '7 years': 7,
        '8 years': 8,
        '9 years': 9,
        '10+ years': 10,
        '< 1 year': 0,
        'n/a':None,
    }
    try:
        d = switcher[argument['employment_length']]    
    except:
        d = None
    return d

loans['employment_length_clean'] = loans.apply (lambda row: clean_emp_length(row),axis=1)
loans_predict['employment_length_clean'] = loans_predict.apply (lambda row: clean_emp_length(row),axis=1)

loans.head()
#np.unique(loans['loan_length'])
np.unique(loans['loan_purpose'])

array(['car', 'credit_card', 'debt_consolidation', 'educational',
       'home_improvement', 'house', 'major_purchase', 'medical', 'moving',
       'other', 'renewable_energy', 'small_business', 'vacation', 'wedding'], dtype=object)

In [737]:
from sklearn.feature_extraction import DictVectorizer

# comb_dict = loans[['loan_length']].to_dict(orient='records')
# vec = DictVectorizer()
# home = 2*vec.fit_transform(comb_dict).toarray()-1
# home[:2]

# df_vector = pd.DataFrame(home[:,0:])
# vector_columns = vec.get_feature_names()
# df_vector.columns = vector_columns[0:]
# df_vector.index = loans.index
# df_vector.head()

# loans = loans.join(df_vector)
# loans.head()

comb_dict = loans[['loan_purpose']].to_dict(orient='records')
vec = DictVectorizer()
home = 2*vec.fit_transform(comb_dict).toarray()-1
home[:14]

df_vector = pd.DataFrame(home[:,0:])
vector_columns = vec.get_feature_names()
df_vector.columns = vector_columns[0:]
df_vector.index = loans.index
df_vector.head()

loans = loans.join(df_vector)
loans.head()


# comb_dict = loans_predict[['loan_length']].to_dict(orient='records')
# vec = DictVectorizer()
# home = 2*vec.fit_transform(comb_dict).toarray()-1
# home[:2]

# df_vector = pd.DataFrame(home[:,0:])
# vector_columns = vec.get_feature_names()
# df_vector.columns = vector_columns[0:]
# df_vector.index = loans_predict.index
# df_vector.head()

# loans_predict = loans_predict.join(df_vector)
# loans_predict.head()

comb_dict = loans_predict[['loan_purpose']].to_dict(orient='records')
vec = DictVectorizer()
home = 2*vec.fit_transform(comb_dict).toarray()-1
home[:14]

df_vector = pd.DataFrame(home[:,0:])
vector_columns = vec.get_feature_names()
df_vector.columns = vector_columns[0:]
df_vector.index = loans_predict.index
df_vector.head()

loans_predict = loans_predict.join(df_vector)
loans_predict.head()

,loan_id,amount_requested,amount_funded_by_investors,interest_rate,loan_length,credit_grade,loan_title,loan_purpose,monthly_payment,total_amount_funded,debttoincome_ratio,city,state,home_ownership,monthly_income,fico_range,earliest_credit_line,open_credit_lines,total_credit_lines,revolving_credit_balance,revolving_line_utilization,inquiries_in_the_last_6_months,accounts_now_delinquent,delinquent_amount,delinquencies_last_2_yrs,months_since_last_delinquency,public_records_on_file,months_since_last_record,education,employment_length,status,int_rate_clean,debttoincomeratio_clean,revolving_line_utilization_clean,loan_length_clean,employment_length_clean,loan_purpose=car,loan_purpose=credit_card,loan_purpose=debt_consolidation,loan_purpose=educational,loan_purpose=home_improvement,loan_purpose=house,loan_purpose=major_purchase,loan_purpose=medical,loan_purpose=moving,loan_purpose=other,loan_purpose=renewable_energy,loan_purpose=small_business,loan_purpose=vacation,loan_purpose=wedding
0,1856772,10000,10000.00,10.16%,36 months,B1,Home improvement,home_improvement,323.43,10000,17.45%,fort worth,TX,OWN,4458.33,730-734,11/29/85,18.0,35.0,9973.0,19.70%,1.0,0.0,0.0,0.0,NaN,1.0,86.0,NaN,4 years,?,0.1016,None,0.197,1,4.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,544915,4800,4800.00,13.61%,36 months,C2,My Loan,debt_consolidation,163.15,4800,15.79%,CINCINNATI,OH,OWN,1647.00,675-679,6/13/04,10.0,13.0,6636.0,45.50%,0.0,0.0,0.0,0.0,39.0,0.0,NaN,NaN,< 1 year,?,0.1361,None,0.455,1,0.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,2079551,10000,10000.00,12.12%,36 months,B3,consoliate,debt_consolidation,332.72,10000,14.84%,Highlands Ranch,CO,RENT,7333.33,710-714,7/20/89,8.0,40.0,14888.0,24.10%,2.0,0.0,0.0,1.0,8.0,0.0,NaN,NaN,n/a,?,0.1212,None,0.241,1,NaN,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
3,2514828,5350,5350.00,15.80%,36 months,C3,Debt Consoldation,debt_consolidation,0.00,5350,21.36%,LITTLE ELM,TX,MORTGAGE,3333.33,675-679,11/10/02,9.0,18.0,9879.0,55.80%,1.0,0.0,0.0,1.0,12.0,0.0,NaN,NaN,1 year,?,0.1580,None,0.558,1,1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,396145,13000,2997.38,14.74%,36 months,D3,i always make my payment.,debt_consolidation,448.98,13000,16.39%,louisville,KY,MORTGAGE,2916.67,675-679,8/30/01,9.0,9.0,21124.0,87.30%,3.0,0.0,0.0,0.0,NaN,0.0,NaN,Jefferson Community College-Louisville,3 years,?,0.1474,None,0.873,1,3.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [738]:
np.unique(loans['home_ownership'])

array(['MORTGAGE', 'NONE', 'OTHER', 'OWN', 'RENT'], dtype=object)

In [739]:
# comb_dict = loans[['home_ownership']].to_dict(orient='records')
# vec = DictVectorizer()
# home = 2*vec.fit_transform(comb_dict).toarray()-1
# home[:5]

In [740]:
# df_vector = pd.DataFrame(home[:,0:])
# vector_columns = vec.get_feature_names()
# df_vector.columns = vector_columns[0:]
# df_vector.index = loans.index
# df_vector.head()

In [741]:
# loans = loans.join(df_vector)

loans = loans.drop(['loan_length','interest_rate','employment_length', 'debttoincome_ratio', 'revolving_line_utilization'],axis=1)
loans.head(n=5)

,loan_id,amount_requested,amount_funded_by_investors,credit_grade,loan_title,loan_purpose,monthly_payment,total_amount_funded,city,state,home_ownership,monthly_income,fico_range,earliest_credit_line,open_credit_lines,total_credit_lines,revolving_credit_balance,inquiries_in_the_last_6_months,accounts_now_delinquent,delinquent_amount,delinquencies_last_2_yrs,months_since_last_delinquency,public_records_on_file,months_since_last_record,education,status,int_rate_clean,debttoincomeratio_clean,revolving_line_utilization_clean,loan_length_clean,employment_length_clean,loan_purpose=car,loan_purpose=credit_card,loan_purpose=debt_consolidation,loan_purpose=educational,loan_purpose=home_improvement,loan_purpose=house,loan_purpose=major_purchase,loan_purpose=medical,loan_purpose=moving,loan_purpose=other,loan_purpose=renewable_energy,loan_purpose=small_business,loan_purpose=vacation,loan_purpose=wedding
0,2227104,12000,12000.00,B4,Credit card refinancing,credit_card,404.97,12000,KINGSBURG,CA,MORTGAGE,4166.67,690-694,11/25/89,10.0,24.0,20229.0,0.0,0.0,0.0,0.0,34.0,0.0,NaN,NaN,0,0.1311,None,0.868,1,7.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,1690660,2000,2000.00,C5,Car financing,car,71.58,2000,FORT LAUDERDALE,FL,OWN,2083.33,660-664,1/27/07,18.0,28.0,6175.0,3.0,0.0,0.0,0.0,30.0,0.0,NaN,NaN,1,0.1727,None,0.368,1,1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,2301695,9000,9000.00,A4,Bundle Loan,debt_consolidation,281.62,9000,PEACHTREE CITY,GA,MORTGAGE,7750.00,690-694,2/26/97,9.0,39.0,11639.0,0.0,0.0,0.0,2.0,10.0,0.0,NaN,NaN,0,0.0790,None,0.466,1,0.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
3,844352,13000,13000.00,B5,Payback,debt_consolidation,431.73,13000,Minneapolis,MN,RENT,5833.33,705-709,10/3/00,12.0,26.0,6696.0,1.0,0.0,0.0,0.0,58.0,0.0,NaN,NaN,1,0.1199,None,0.475,1,5.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,330773,10000,1525.01,B5,Business Loan,other,163.01,5000,reno,NV,MORTGAGE,16666.67,700-704,3/21/88,20.0,30.0,53087.0,1.0,0.0,0.0,0.0,45.0,0.0,NaN,NaN,0,0.1071,None,0.699,1,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0

In [742]:
# #do the same for loans predict
# comb_dict = loans_predict[['home_ownership']].to_dict(orient='records')
# vec = DictVectorizer()
# home = 2*vec.fit_transform(comb_dict).toarray()-1
# home[:5]

# df_vector = pd.DataFrame(home[:,0:])
# vector_columns = vec.get_feature_names()
# df_vector.columns = vector_columns[0:]
# df_vector.index = loans_predict.index
# df_vector.head()

# loans_predict = loans_predict.join(df_vector)

loans_predict = loans_predict.drop(['loan_length','interest_rate','employment_length', 'debttoincome_ratio', 'revolving_line_utilization'],axis=1)
loans_predict.head(n=5)

,loan_id,amount_requested,amount_funded_by_investors,credit_grade,loan_title,loan_purpose,monthly_payment,total_amount_funded,city,state,home_ownership,monthly_income,fico_range,earliest_credit_line,open_credit_lines,total_credit_lines,revolving_credit_balance,inquiries_in_the_last_6_months,accounts_now_delinquent,delinquent_amount,delinquencies_last_2_yrs,months_since_last_delinquency,public_records_on_file,months_since_last_record,education,status,int_rate_clean,debttoincomeratio_clean,revolving_line_utilization_clean,loan_length_clean,employment_length_clean,loan_purpose=car,loan_purpose=credit_card,loan_purpose=debt_consolidation,loan_purpose=educational,loan_purpose=home_improvement,loan_purpose=house,loan_purpose=major_purchase,loan_purpose=medical,loan_purpose=moving,loan_purpose=other,loan_purpose=renewable_energy,loan_purpose=small_business,loan_purpose=vacation,loan_purpose=wedding
0,1856772,10000,10000.00,B1,Home improvement,home_improvement,323.43,10000,fort worth,TX,OWN,4458.33,730-734,11/29/85,18.0,35.0,9973.0,1.0,0.0,0.0,0.0,NaN,1.0,86.0,NaN,?,0.1016,None,0.197,1,4.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,544915,4800,4800.00,C2,My Loan,debt_consolidation,163.15,4800,CINCINNATI,OH,OWN,1647.00,675-679,6/13/04,10.0,13.0,6636.0,0.0,0.0,0.0,0.0,39.0,0.0,NaN,NaN,?,0.1361,None,0.455,1,0.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,2079551,10000,10000.00,B3,consoliate,debt_consolidation,332.72,10000,Highlands Ranch,CO,RENT,7333.33,710-714,7/20/89,8.0,40.0,14888.0,2.0,0.0,0.0,1.0,8.0,0.0,NaN,NaN,?,0.1212,None,0.241,1,NaN,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
3,2514828,5350,5350.00,C3,Debt Consoldation,debt_consolidation,0.00,5350,LITTLE ELM,TX,MORTGAGE,3333.33,675-679,11/10/02,9.0,18.0,9879.0,1.0,0.0,0.0,1.0,12.0,0.0,NaN,NaN,?,0.1580,None,0.558,1,1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,396145,13000,2997.38,D3,i always make my payment.,debt_consolidation,448.98,13000,louisville,KY,MORTGAGE,2916.67,675-679,8/30/01,9.0,9.0,21124.0,3.0,0.0,0.0,0.0,NaN,0.0,NaN,Jefferson Community College-Louisville,?,0.1474,None,0.873,1,3.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [743]:
# loans.loan_purpose = pd.Categorical(loans.loan_purpose)
# loans['loan_purpose_code'] = loans.loan_purpose.cat.codes
# loans.head(n=100)

loans.credit_grade = pd.Categorical(loans.credit_grade)
loans['credit_grade_code'] = loans.credit_grade.cat.codes
loans.head(n=100)

loans.state = pd.Categorical(loans.state)
loans['state_code'] = loans.state.cat.codes
loans.head(n=100)

loans.fico_range = pd.Categorical(loans.fico_range)
loans['fico_range_code'] = loans.fico_range.cat.codes
loans.head(n=10)

loans.home_ownership = pd.Categorical(loans.home_ownership)
loans['home_ownership_code'] = loans.home_ownership.cat.codes
loans.head(n=100)

# loans_predict.loan_purpose = pd.Categorical(loans_predict.loan_purpose)
# loans_predict['loan_purpose_code'] = loans_predict.loan_purpose.cat.codes

loans_predict.credit_grade = pd.Categorical(loans_predict.credit_grade)
loans_predict['credit_grade_code'] = loans_predict.credit_grade.cat.codes

loans_predict.state = pd.Categorical(loans_predict.state)
loans_predict['state_code'] = loans_predict.state.cat.codes

loans_predict.fico_range = pd.Categorical(loans_predict.fico_range)
loans_predict['fico_range_code'] = loans_predict.fico_range.cat.codes

loans_predict.home_ownership = pd.Categorical(loans_predict.home_ownership)
loans_predict['home_ownership_code'] = loans_predict.home_ownership.cat.codes
loans_predict.head(n=100)

loans_predict = loans_predict.rename(columns={'status_fully_paid=1,_not_paid=0': 'status'})
loans_predict.head(n=10)

# for index, row in loans_predict.iterrows():
#     val = pd.isnull(row['education']) 
#     if val == True:
#         row['education'] = 0
#     else:
#         row['education'] = 1

loans_predict[['education']] = loans_predict[['education']].where(loans_predict[['education']].isnull(), 1).fillna(0).astype(int)
loans[['education']] = loans[['education']].where(loans[['education']].isnull(), 1).fillna(0).astype(int)
loans_predict.head(n=10)

#print (loans.dtypes)

,loan_id,amount_requested,amount_funded_by_investors,credit_grade,loan_title,loan_purpose,monthly_payment,total_amount_funded,city,state,home_ownership,monthly_income,fico_range,earliest_credit_line,open_credit_lines,total_credit_lines,revolving_credit_balance,inquiries_in_the_last_6_months,accounts_now_delinquent,delinquent_amount,delinquencies_last_2_yrs,months_since_last_delinquency,public_records_on_file,months_since_last_record,education,status,int_rate_clean,debttoincomeratio_clean,revolving_line_utilization_clean,loan_length_clean,employment_length_clean,loan_purpose=car,loan_purpose=credit_card,loan_purpose=debt_consolidation,loan_purpose=educational,loan_purpose=home_improvement,loan_purpose=house,loan_purpose=major_purchase,loan_purpose=medical,loan_purpose=moving,loan_purpose=other,loan_purpose=renewable_energy,loan_purpose=small_business,loan_purpose=vacation,loan_purpose=wedding,credit_grade_code,state_code,fico_range_code,home_ownership_code
0,1856772,10000,10000.00,B1,Home improvement,home_improvement,323.43,10000,fort worth,TX,OWN,4458.33,730-734,11/29/85,18.0,35.0,9973.0,1.0,0.0,0.0,0.0,NaN,1.0,86.0,0,?,0.1016,None,0.197,1,4.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,5,42,18,3
1,544915,4800,4800.00,C2,My Loan,debt_consolidation,163.15,4800,CINCINNATI,OH,OWN,1647.00,675-679,6/13/04,10.0,13.0,6636.0,0.0,0.0,0.0,0.0,39.0,0.0,NaN,0,?,0.1361,None,0.455,1,0.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,11,34,7,3
2,2079551,10000,10000.00,B3,consoliate,debt_consolidation,332.72,10000,Highlands Ranch,CO,RENT,7333.33,710-714,7/20/89,8.0,40.0,14888.0,2.0,0.0,0.0,1.0,8.0,0.0,NaN,0,?,0.1212,None,0.241,1,NaN,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,7,5,14,4
3,2514828,5350,5350.00,C3,Debt Consoldation,debt_consolidation,0.00,5350,LITTLE ELM,TX,MORTGAGE,3333.33,675-679,11/10/02,9.0,18.0,9879.0,1.0,0.0,0.0,1.0,12.0,0.0,NaN,0,?,0.1580,None,0.558,1,1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,12,42,7,0
4,396145,13000,2997.38,D3,i always make my payment.,debt_consolidation,448.98,13000,louisville,KY,MORTGAGE,2916.67,675-679,8/30/01,9.0,9.0,21124.0,3.0,0.0,0.0,0.0,NaN,0.0,NaN,1,?,0.1474,None,0.873,1,3.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,17,17,7,0
5,734817,21000,20925.00,B2,Credit Card Refinancing,credit_card,677.62,21000,San Francisco,CA,RENT,6250.00,730-734,7/10/01,8.0,20.0,21102.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0,?,0.1000,None,0.630,1,2.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,6,4,18,4
6,396154,10500,6165.53,E1,4WD Chevy,car,367.52,10500,Leavenworth,KS,MORTGAGE,5000.00,675-679,4/9/94,15.0,19.0,24151.0,3.0,0.0,0.0,0.0,NaN,0.0,NaN,1,?,0.1568,None,0.611,1,6.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,20,16,7,0
7,637408,8000,8000.00,C1,High Interest Credit Card Refinancing,credit_card,266.60,8000,Griffin,GA,RENT,5083.33,690-694,5/12/01,7.0,13.0,9433.0,5.0,0.0,0.0,0.0,NaN,0.0,NaN,0,?,0.1223,None,0.763,1,1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,10,10,10,4
8,493460,10000,10000.00,C1,Bridge Loan for Start Up Paralegal Biz,small_business,335.67,10000,Dallas,TX,RENT,6666.67,705-709,3/29/95,7.0,28.0,0.0,1.0,0.0,0.0,0.0,26.0,0.0,NaN,1,?,0.1273,None,0.000,1,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,10,42,13,4
9,2370413,29375,29375.00,B2,Debt consolidation,debt_consolidation,963.65,29375,Belton,MO,MORTGAGE,5833.33,715-719,11/29/97,14.0,23.0,20804.0,0.0,0.0,0.0,0.0,72.0,0.0,NaN,0,?,0.1114,None,0.556,1,3.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,6,24,15,0

In [744]:
new_df = loans.copy()

new_df = new_df.drop(['credit_grade', 'loan_title', 'loan_purpose', 'state', 'city', 'fico_range',
                   'city', 'earliest_credit_line', 'home_ownership'],axis=1)
new_df.head(n=5)

cols = list(new_df)
cols.insert(0, cols.pop(cols.index('status')))
new_df = new_df.ix[:, cols]
new_df.head()

,status,loan_id,amount_requested,amount_funded_by_investors,monthly_payment,total_amount_funded,monthly_income,open_credit_lines,total_credit_lines,revolving_credit_balance,inquiries_in_the_last_6_months,accounts_now_delinquent,delinquent_amount,delinquencies_last_2_yrs,months_since_last_delinquency,public_records_on_file,months_since_last_record,education,int_rate_clean,debttoincomeratio_clean,revolving_line_utilization_clean,loan_length_clean,employment_length_clean,loan_purpose=car,loan_purpose=credit_card,loan_purpose=debt_consolidation,loan_purpose=educational,loan_purpose=home_improvement,loan_purpose=house,loan_purpose=major_purchase,loan_purpose=medical,loan_purpose=moving,loan_purpose=other,loan_purpose=renewable_energy,loan_purpose=small_business,loan_purpose=vacation,loan_purpose=wedding,credit_grade_code,state_code,fico_range_code,home_ownership_code
0,0,2227104,12000,12000.00,404.97,12000,4166.67,10.0,24.0,20229.0,0.0,0.0,0.0,0.0,34.0,0.0,NaN,0,0.1311,None,0.868,1,7.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,8,4,10,0
1,1,1690660,2000,2000.00,71.58,2000,2083.33,18.0,28.0,6175.0,3.0,0.0,0.0,0.0,30.0,0.0,NaN,0,0.1727,None,0.368,1,1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,14,9,4,3
2,0,2301695,9000,9000.00,281.62,9000,7750.00,9.0,39.0,11639.0,0.0,0.0,0.0,2.0,10.0,0.0,NaN,0,0.0790,None,0.466,1,0.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,3,10,10,0
3,1,844352,13000,13000.00,431.73,13000,5833.33,12.0,26.0,6696.0,1.0,0.0,0.0,0.0,58.0,0.0,NaN,0,0.1199,None,0.475,1,5.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,9,23,13,4
4,0,330773,10000,1525.01,163.01,5000,16666.67,20.0,30.0,53087.0,1.0,0.0,0.0,0.0,45.0,0.0,NaN,0,0.1071,None,0.699,1,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,9,32,12,0

In [745]:
test_df = loans_predict.copy()

test_df = test_df.drop(['credit_grade', 'loan_title', 'loan_purpose', 'state', 'city', 'fico_range',
                   'city', 'earliest_credit_line', 'home_ownership'],axis=1)
test_df.head(n=5)

cols = list(test_df)
cols.insert(0, cols.pop(cols.index('status')))
test_df = test_df.ix[:, cols]
test_df.head()

,status,loan_id,amount_requested,amount_funded_by_investors,monthly_payment,total_amount_funded,monthly_income,open_credit_lines,total_credit_lines,revolving_credit_balance,inquiries_in_the_last_6_months,accounts_now_delinquent,delinquent_amount,delinquencies_last_2_yrs,months_since_last_delinquency,public_records_on_file,months_since_last_record,education,int_rate_clean,debttoincomeratio_clean,revolving_line_utilization_clean,loan_length_clean,employment_length_clean,loan_purpose=car,loan_purpose=credit_card,loan_purpose=debt_consolidation,loan_purpose=educational,loan_purpose=home_improvement,loan_purpose=house,loan_purpose=major_purchase,loan_purpose=medical,loan_purpose=moving,loan_purpose=other,loan_purpose=renewable_energy,loan_purpose=small_business,loan_purpose=vacation,loan_purpose=wedding,credit_grade_code,state_code,fico_range_code,home_ownership_code
0,?,1856772,10000,10000.00,323.43,10000,4458.33,18.0,35.0,9973.0,1.0,0.0,0.0,0.0,NaN,1.0,86.0,0,0.1016,None,0.197,1,4.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,5,42,18,3
1,?,544915,4800,4800.00,163.15,4800,1647.00,10.0,13.0,6636.0,0.0,0.0,0.0,0.0,39.0,0.0,NaN,0,0.1361,None,0.455,1,0.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,11,34,7,3
2,?,2079551,10000,10000.00,332.72,10000,7333.33,8.0,40.0,14888.0,2.0,0.0,0.0,1.0,8.0,0.0,NaN,0,0.1212,None,0.241,1,NaN,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,7,5,14,4
3,?,2514828,5350,5350.00,0.00,5350,3333.33,9.0,18.0,9879.0,1.0,0.0,0.0,1.0,12.0,0.0,NaN,0,0.1580,None,0.558,1,1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,12,42,7,0
4,?,396145,13000,2997.38,448.98,13000,2916.67,9.0,9.0,21124.0,3.0,0.0,0.0,0.0,NaN,0.0,NaN,1,0.1474,None,0.873,1,3.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,17,17,7,0

# Modeling

In [746]:
from sklearn.model_selection import train_test_split

new_df = new_df.fillna(0)
test_df = test_df.fillna(0)

X = new_df.iloc[:, 1:]  # select columns 1 through end
y = new_df.iloc[:, 0]   # select first column, the status 

X_test = test_df.iloc[:, 1:]  # select columns 1 through end
y_test = test_df.iloc[:, 0]

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

X_test.head()

,loan_id,amount_requested,amount_funded_by_investors,monthly_payment,total_amount_funded,monthly_income,open_credit_lines,total_credit_lines,revolving_credit_balance,inquiries_in_the_last_6_months,accounts_now_delinquent,delinquent_amount,delinquencies_last_2_yrs,months_since_last_delinquency,public_records_on_file,months_since_last_record,education,int_rate_clean,debttoincomeratio_clean,revolving_line_utilization_clean,loan_length_clean,employment_length_clean,loan_purpose=car,loan_purpose=credit_card,loan_purpose=debt_consolidation,loan_purpose=educational,loan_purpose=home_improvement,loan_purpose=house,loan_purpose=major_purchase,loan_purpose=medical,loan_purpose=moving,loan_purpose=other,loan_purpose=renewable_energy,loan_purpose=small_business,loan_purpose=vacation,loan_purpose=wedding,credit_grade_code,state_code,fico_range_code,home_ownership_code
0,1856772,10000,10000.00,323.43,10000,4458.33,18.0,35.0,9973.0,1.0,0.0,0.0,0.0,0.0,1.0,86.0,0,0.1016,0,0.197,1,4.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,5,42,18,3
1,544915,4800,4800.00,163.15,4800,1647.00,10.0,13.0,6636.0,0.0,0.0,0.0,0.0,39.0,0.0,0.0,0,0.1361,0,0.455,1,0.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,11,34,7,3
2,2079551,10000,10000.00,332.72,10000,7333.33,8.0,40.0,14888.0,2.0,0.0,0.0,1.0,8.0,0.0,0.0,0,0.1212,0,0.241,1,0.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,7,5,14,4
3,2514828,5350,5350.00,0.00,5350,3333.33,9.0,18.0,9879.0,1.0,0.0,0.0,1.0,12.0,0.0,0.0,0,0.1580,0,0.558,1,1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,12,42,7,0
4,396145,13000,2997.38,448.98,13000,2916.67,9.0,9.0,21124.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.1474,0,0.873,1,3.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,17,17,7,0

In [747]:
# from sklearn.neighbors import KNeighborsClassifier

# nbr = KNeighborsClassifier(n_neighbors=9)
# nbr.fit(X_train, y_train)
# #nbr.score(X_test, y_test)

In [748]:
# from sklearn.tree import DecisionTreeClassifier

# tree = DecisionTreeClassifier(criterion = 'entropy', max_depth=3, random_state=0)
# tree.fit(X_train.values, y_train)
# #X_test["predicted"] = tree.predict(X_test)
# #X_test.head()
# #tree.score(X_test, y_test)

# #submission = X_test[['loan_id','predicted']]
# #submission.head()
# #submission.to_csv('Submission.csv', encoding='utf-8', index=False)

In [749]:
# from sklearn.ensemble import RandomForestClassifier

# clf = RandomForestClassifier()
# clf.fit(X_train, y_train)
# #clf.score(X_test, y_test)

In [750]:
# from sklearn.model_selection import GridSearchCV
# from sklearn.linear_model import LogisticRegression

# params = [{
#     "C": [.1 , 1, 10, 100]
# }]
# clf = GridSearchCV(LogisticRegression(), param_grid = params, cv = 5)
# clf.fit(X_train.values, y_train)
# #clf.score(X_test, y_test)
# #clf.best_score_

In [751]:
import xgboost as xgb
from sklearn.metrics import precision_score

dtrain = xgb.DMatrix(X, label=y)
dtest = xgb.DMatrix(X_test)

param = {
    'max_depth': 4,  # the maximum depth of each tree
    'eta': 0.3,  # the training step for each iteration
    'silent': 1,  # logging mode - quiet
    'objective': 'multi:softprob',  # error evaluation for multiclass training
    'num_class': 44
}  # the number of classes that exist in this datset
num_round = 20  # the number of training iterations

bst = xgb.train(param, dtrain, num_round)
preds = bst.predict(dtest)

best_preds = np.asarray([np.argmax(line) for line in preds])
X_test['preds']= best_preds
X_test.head()

submission = X_test[['loan_id','preds']]
#print (precision_score(y_test, best_preds, average='macro'))
submission.to_csv('SubmissionDayFinal.csv', encoding='utf-8', index=False)
submission.head()

   loan_id  preds
0  1856772      0
1   544915      1
2  2079551      0
3  2514828      0
4   396145      1

In [752]:
# from sklearn.metrics import accuracy_score
# from xgboost import XGBClassifier

# param = {
#     'max_depth': 3,  # the maximum depth of each tree
#     'learning_rate': 0.3,  # the training step for each iteration
#     'silent': 1,  # logging mode - quiet
#     'objective': 'multi:softprob',  # error evaluation for multiclass training
#     'num_class': 30}  # the number of classes that exist in this datset

# model = XGBClassifier(**param)
# model.fit(X_train, y_train)
# y_pred = model.predict(X_test)
# predictions = [round(value) for value in y_pred]
# accuracy = accuracy_score(y_test, predictions)
# print("Accuracy: %.2f%%" % (accuracy * 100.0))